version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0-beta.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: DummySecret
  apollo-graphql-server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: apollo-server:latest
    depends_on:
    - "graphql-engine"
    environment: 
      - PORT=4000
      - NODE_ENV=development
      - HASURA_END_POINT=http://graphql-engine:8080/v1/graphql
      - HASURA_ADMIN_SECRET=DummySecret
    ports:
      - 4000:4000
volumes:
  db_data: